version: "3.7"

x-auth-args: &auth-args
  GITLAB_USERNAME: ${GITLAB_USERNAME}
  GITLAB_PASSWORD: ${GITLAB_PASSWORD}

services:

  broker:
    image: code.ornl.gov:4567/intersect/sdk/broker/0.2.0
    ports:
      - "1883:1883"
    networks:
      - intersect
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  hello-world-adapter:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
         <<: *auth-args
    image: "intersect-examples-hello-world"
    command: ["python", "adapter.py"]
    networks:
      - intersect
    volumes:
      - '.:/app'
    depends_on:
      broker:
        condition: service_healthy

  hello-world-requestor:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
         <<: *auth-args
    image: "intersect-examples-hello-world"
    command: ["python", "requestor.py"]
    networks:
      - intersect
    volumes:
      - '.:/app'
    depends_on:
      - hello-world-adapter

networks:
  intersect:
    name: intersect
