[tool.poetry]
name = "intersect"
version = "0.1"
description = "Python interface for INTERSECT SDK"
authors = [
    'Matthew Baker <bakermb@ornl.gov>',
    'Lance Drane <dranelt@ornl.gov>',
    'John Hetrick <hetrickjm@ornl.gov>',
    'Seth Hitefield <hitefieldsd@ornl.gov>',
    'Marshall McDonnell <mcdonnellmt@ornl.gov>',
    'Jesse McGaha <mcgahajr@ornl.gov>',
    'Robert Smith <smithrw@ornl.gov>',
    'Gavin Wiggins <wigginsg@ornl.gov>',
]
packages = [
    { include = "intersect", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8.10"
protobuf = "^3.16"
pydantic = "^1.10.7"
retrying = "^1.3.4"
paho-mqtt = "^1.6.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
flake8 = "^6.0.0"
pre-commit = "^3.3.1"
black = "^23.3.0"
isort = "^5.12.0"
sphinx = "^5.3.0"
furo = "^2023.3.27"

[tool.poetry.group.amqp.dependencies]
pika = "^1.3.2"

[build-system]
requires = ["poetry-core>=1.3.1"]
build-backend = "poetry.core.masonry.api"
