[project]
name = "intersect"
description = "Python SDK to interact with INTERSECT"
authors = [
    {name = "Matthew Baker", email = "bakermb@ornl.gov"},
    {name = "Lance Drane", email = "dranelt@ornl.gov"},
    {name = "John Hetrick", email = "hetrickjm@ornl.gov"},
    {name = "Seth Hitefield", email = "hitefieldsd@ornl.gov"},
    {name = "Marshall McDonnell", email = "mcdonnellmt@ornl.gov"},
    {name = "Jesse McGaha", email = "mcgahajr@ornl.gov"},
    {name = "Robert Smith", email = "smithrw@ornl.gov"},
    {name = "Gavin Wiggins", email = "wigginsg@ornl.gov"},
]
readme = "README.md"
#license = {text = "BSD-3-Clause"}
requires-python = ">=3.8.10,<4.0"
keywords = ["intersect"]
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "protobuf>=3.16,<4.0",
    "pydantic>=1.10.7,<2.0.0",
    "retrying>=1.3.4,<2.0.0",
    "paho-mqtt>=1.6.1,<2.0.0",
    "jsonschema>=4.17.3,<5.0.0",
]

[project.optional-dependencies]
amqp = [
    "pika>=1.3.2,<2.0.0",
]
yaml = [
    "pyyaml>=6.0,<7.0",
]
# this is unnecessary for python environments >= 3.11, as the SDK only reads TOML but does not write TOML
toml = [
    "tomli>=2.0.1,<3.0.0",
]

[tool.pdm.dev-dependencies]
lint = [
    "pre-commit>=3.3.1",
    "flake8>=6.0.0",
    "black>=23.3.0",
    "isort>=5.12.0",
    "mypy>=1.3.0",
    "types-pyyaml>=6.0.12.10",
    "types-jsonschema>=4.17.0.8",
    "types-protobuf>=4.23.0.1",
    "bandit>=1.7.5",
    "flake8-bugbear>=23.6.5",
]
test = [
    "pytest>=7.3.2",
    "pytest-cov>=4.1.0",
    "httpretty>=1.1.4",
]
doc = [
    "sphinx>=5.3.0",
    "furo>=2023.3.27",
]

[tool.pdm.scripts]
test = "pytest tests/unit/ --cov=."
test-debug = "pytest tests/unit/ --cov=. -s"
test-report = "pytest tests/unit/ --cov=. --junitxml=reports/report_unit.xml"
test-coverage = "pytest --cov=. --cov-fail-under=70 --cov-report=html:reports/htmlcov/ --cov-report=xml:reports/coverage.xml tests/unit/"
integration = "pytest tests/integration/"
integration-debug = "pytest tests/integration/ -s"
integration-report = "pytest tests/integration/ --junitxml=reports/report_integration.xml"
integration-coverage = "pytest --cov=. --cov-fail-under=70 --cov-report=html:reports/htmlcov/ --cov-report=xml:reports/coverage.xml tests/integration/"
lint = {composite = ["lint-isort", "lint-black", "lint-flake8", "lint-mypy", "lint-bandit"]}
lint-black = "black ."
lint-isort = "isort --filter-files ."
lint-flake8 = "flake8"
lint-mypy = "mypy src/intersect/"
lint-bandit = "bandit -c pyproject.toml -r ."

[tool.pdm.build]
package-dir = "src"

[tool.pdm.version]
source = "file"
path = "src/intersect/version.py"

[tool.black]
color = true
line-length = 100
target-version = ['py38']
include = '.pyi?$'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
profile = "black"
line_length = 100

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true

[tool.bandit]
exclude_dirs = [".venv", "tests"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
