[project]
name = "intersect"
version = "0.2.0"
description = "Python SDK to interact with INTERSECT"
authors = [
    {name = "Matthew Baker", email = "bakermb@ornl.gov"},
    {name = "Lance Drane", email = "dranelt@ornl.gov"},
    {name = "John Hetrick", email = "hetrickjm@ornl.gov"},
    {name = "Seth Hitefield", email = "hitefieldsd@ornl.gov"},
    {name = "Marshall McDonnell", email = "mcdonnellmt@ornl.gov"},
    {name = "Jesse McGaha", email = "mcgahajr@ornl.gov"},
    {name = "Robert Smith", email = "smithrw@ornl.gov"},
    {name = "Gavin Wiggins", email = "wigginsg@ornl.gov"},
]
readme = "README.md"
#license = {text = "BSD-3-Clause"}
requires-python = ">=3.8.10,<4.0"
dependencies = [
    "protobuf>=3.16,<4.0",
    "pydantic>=1.10.7,<2.0.0",
    "retrying>=1.3.4,<2.0.0",
    "paho-mqtt>=1.6.1,<2.0.0",
    "jsonschema>=4.17.3,<5.0.0",
]

[project.optional-dependencies]
amqp = [
    "pika>=1.3.2,<2.0.0",
]
yaml = [
    "pyyaml>=6.0",
]
# this is unnecessary for python environments >= 3.11, as the SDK only reads TOML but does not write TOML
toml = [
    "tomli>=2.0.1",
]

[tool.pdm.dev-dependencies]
lint = [
    "pre-commit>=3.3.1,<4",
    "flake8>=6.0.0,<7",
    "black>=23.3.0,<24",
    "isort>=5.12.0,<6",
    "mypy>=1.3.0,<2",
    "types-pyyaml>=6.0.12.10",
    "types-jsonschema>=4.17.0.8",
    "types-protobuf>=4.23.0.1",
]
test = [
    "pytest>=7.3.1,<8",
]
doc = [
    "sphinx>=5.3.0,<6",
    "furo>=2023.3.27",
]

[tool.pdm.scripts]
test = "pytest tests/"
test-debug = "pytest tests/ -s"
test-with-report = "pytest tests/ --junitxml=report_unit.xml"
test-coverage = "pytest tests/ --cov=. --cov-fail-under=50 --cov-report=html:./htmlcov --cov-report=xml:./coverage.xml"
lint = {composite = ["lint-isort", "lint-black", "lint-flake8", "lint-mypy"]}
lint-black = "black ."
lint-isort = "isort --filter-files ."
lint-flake8 = "flake8"
lint-mypy = "mypy src/intersect/"

[tool.pdm.build]
excludes = ["./**/.git"]
package-dir = "src"
includes = [
    "src/intersect",
]

[tool.black]
line-length = 100
target-version = ['py38']
include = '.pyi?$'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
profile = "black"
line_length = 100

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
