# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\rintersect.sdk\"\xaa\x01\n\x07Generic\x12)\n\x04type\x18\x03 \x01(\x0e\x32\x1b.intersect.sdk.Generic.Type\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\"S\n\x04Type\x12\x0b\n\x07REQUEST\x10\x00\x12\t\n\x05REPLY\x10\x01\x12\t\n\x05\x45VENT\x10\x02\x12\n\n\x06STATUS\x10\x03\x12\x0b\n\x07\x43OMMAND\x10\x04\x12\x0f\n\x0b\x41\x43KNOWLEDGE\x10\x05\"R\n\x06Header\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63reated\x18\x04 \x01(\t\"C\n\x07Request\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x11\n\targuments\x18\x02 \x01(\t\"A\n\x05Reply\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x11\n\targuments\x18\x02 \x01(\t\"A\n\x05\x45vent\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x11\n\targuments\x18\x02 \x01(\t\"?\n\x06Status\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"C\n\x07\x43ommand\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x11\n\targuments\x18\x02 \x01(\t\"G\n\x0b\x41\x63knowledge\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.intersect.sdk.Header\x12\x11\n\targuments\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERIC._serialized_start=30
  _GENERIC._serialized_end=200
  _GENERIC_TYPE._serialized_start=117
  _GENERIC_TYPE._serialized_end=200
  _HEADER._serialized_start=202
  _HEADER._serialized_end=284
  _REQUEST._serialized_start=286
  _REQUEST._serialized_end=353
  _REPLY._serialized_start=355
  _REPLY._serialized_end=420
  _EVENT._serialized_start=422
  _EVENT._serialized_end=487
  _STATUS._serialized_start=489
  _STATUS._serialized_end=552
  _COMMAND._serialized_start=554
  _COMMAND._serialized_end=621
  _ACKNOWLEDGE._serialized_start=623
  _ACKNOWLEDGE._serialized_end=694
# @@protoc_insertion_point(module_scope)
