# common credentials for the broker
broker:
  username: "intersect_username"
  password: "intersect_password"
  # you may need to change "host" if running outside of docker environment
  host: "localhost"
  port: 1883

# most of the "hierarchy" is not relevant for this demo application
hierarchy:
  organization: "Oak Ridge National Laboratory"
  facility: "Hello-World Facility"
  system: "Adapter"
  subsystem: "Adapter"
  # must be unique
  service: "Adapter"
