BASE_RESPONSE_ATTR = '__is_intersect_response__'
BASE_STATUS_ATTR = '__is_intersect_status__'
BASE_EVENT_ATTR = '__is_intersect_event__'
# in theory, as long as the next attributes are unique, they can be any string
REQUEST_CONTENT = '__request_content_type__'
RESPONSE_CONTENT = '__response_content_type__'
RESPONSE_DATA = '__response_data_transfer_handler__'
STRICT_VALIDATION = '__strict_validation__'
SHUTDOWN_KEYS = '__ignore_message__'
EVENT_ATTR_KEY = '__intersect_sdk_events__'
