name: Release to PyPi

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.8"
          cache: true
      - name: Publish package to PyPI
        env:
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: pdm publish --username __token__ --repository pypi
      - name: upload to github release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # assume any version with "a" (gets "ALPHA") or "b" (gets BETA) or "rc" (release candidates) will be a prerelease
          PRE_RELEASE: "${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}"
        with:
          args: dist/*
